server:
  port: 8240
  servlet:
    context-path: /api/v1/service/monitor
  tomcat:
    # 2024-12-9  14:17-配置web服务线程的核心线程和最大线程数量
    threads:
      min-spare: 10
      max: 100
    accept-count: 100 # 2024-12-9  14:17-设置请求缓存队列的长度，用于在服务器高负载的情况下临时放置请求


spring:

  # 2024-12-9  14:17-配置MySQL数据库源
  datasource:
    # 2024-12-9  14:17-调整时区为北京时间，以避免自动填充日期时间时出现8个小时的时间差
    url: jdbc:mysql://${ip.physical.self-host:127.0.0.1}:4407/ptp_web?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true # 2024-6-1  23:50-必须要加 allowPublicKeyRetrieval=true ，否则会报错
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ptp_backend
    password: 7758521
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 连接池的最小空闲数量
      min-idle: 5
      # 连接池最大连接数量
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 既作为检测的间隔时间又作为testWhileIdle执行的依据
      time-between-eviction-runs-millis: 60000
      # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接(配置连接在池中的最小生存时间)
      min-evictable-idle-time-millis: 30000
      # 用来检测数据库连接是否有效的sql 必须是一个查询语句(oracle中为 select 1 from dual)
      validation-query: select 1 from dual
      # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      # 是否缓存preparedStatement, 也就是PSCache,PSCache对支持游标的数据库性能提升巨大，比如说oracle,在mysql下建议关闭。
      pool-prepared-statements: false
      # 置监控统计拦截的filters，去掉后监控界面sql无法统计，stat: 监控统计、Slf4j:日志记录、waLL: 防御sqL注入
      filters: stat,wall,slf4j
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: -1
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      # connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000


  # 2024-12-9  14:17-集成Redis所需配置
  data:
    redis:
      host: ${ip.physical.self-host:127.0.0.1}
      port: 7001
      username: default
      password: root
      timeout: 5s # 2024-6-10  22:15-读超时
      connect-timeout: 5s # 2024-6-10  22:16-连接超时
      jedis:
        pool:
          max-active: 8 # 2024-6-10  22:16-连接池最大连接数
          max-wait: -1 # 2024-6-10  22:16-连接池最大阻塞空闲时间(负数表示无限制)
          max-idle: 8 # 2024-6-10  22:16-连接池最大空闲连接数
          min-idle: 0 # 2024-6-10  22:16-连接池最小空闲连接数


  cloud:
    # 2024-12-9  14:17-sentinel相关配置
    sentinel:
      transport:
        dashboard: ${ip.physical.self-host:127.0.0.1}:9888
      log:
        dir: D:\JavaProjects\ptp-web-backend\logs\sentinel\service\monitor
        switch-pid: true


# 2024-12-9  14:17-Knife4j相关配置
knife4j:
  enable: true
  setting:
    language: zh_cn
  cors: true


# 2024-12-9  14:17-OpenAPI文档相关配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    csrf:
      enabled: true
    path: /swagger-ui.html


# 2024-12-16  13:47-Docker客户端的相关配置
docker:
  host: tcp://${ip.physical.docker-ip}:2375
  api-version: 1.47
  # 2024-12-16  15:14-下面的配置为容器名以及其对应的容器ID的映射
  containers:
    ptp-backend-mysql-1: ca8129bec3d5