server:
  port: 8080
  servlet:
    context-path: /api/v1/web


# 2024-3-16  19:34-项目基本配置
spring:
  datasource:
    # 2024-6-2  21:38-调整时区为北京时间，以避免自动填充日期时间时出现8个小时的时间差
    url: jdbc:mysql://127.0.0.1:4407/ptp_web?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true # 2024-4-8  22:14-必须要加 allowPublicKeyRetrieval=true ，否则会报错
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ptp_backend
    password: 7758521
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 初始化时建立物理连接的个数
      initial-size: 5
      # 连接池的最小空闲数量
      min-idle: 5
      # 连接池最大连接数量
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 既作为检测的间隔时间又作为testWhileIdle执行的依据
      time-between-eviction-runs-millis: 60000
      # 销毁线程时检测当前连接的最后活动时间和当前时间差大于该值时，关闭当前连接(配置连接在池中的最小生存时间)
      min-evictable-idle-time-millis: 30000
      # 用来检测数据库连接是否有效的sql 必须是一个查询语句(oracle中为 select 1 from dual)
      validation-query: select 1 from dual
      # 申请连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-borrow: false
      # 归还连接时会执行validationQuery检测连接是否有效,开启会降低性能,默认为true
      test-on-return: false
      # 是否缓存preparedStatement, 也就是PSCache,PSCache对支持游标的数据库性能提升巨大，比如说oracle,在mysql下建议关闭。
      pool-prepared-statements: false
      # 置监控统计拦截的filters，去掉后监控界面sql无法统计，stat: 监控统计、Slf4j:日志记录、waLL: 防御sqL注入
      filters: stat,wall,slf4j
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: -1
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      # connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000

      web-stat-filter:
        # 是否启用StatFilter默认值true
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤的格式
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico

      stat-view-servlet:
        # 是否启用StatViewServlet默认值true
        enabled: true
        # 访问路径为/druid时，跳转到StatViewServlet
        url-pattern: /druid/*
        # 是否能够重置数据
        reset-enable: false
        # 需要账号密码才能访问控制台，默认为root
        login-username: druid
        login-password: druid
        # IP白名单
        allow: 127.0.0.1
        # IP黑名单（共同存在时，deny优先于allow）
        deny:

        # 2024-4-4  20:30-集成Redis所需配置
  data:
    redis:
      host: 127.0.0.1
      port: 7001
      username: default
      password: root
      timeout: 5s # 2024-6-6  22:40-读超时
      connect-timeout: 5s # 2024-6-6  22:41-连接超时
      jedis:
        pool:
          max-active: 8 # 2024-4-7  9:29-连接池最大连接数
          max-wait: -1 # 2024-4-7  9:30-连接池最大阻塞空闲时间(负数表示无限制)
          max-idle: 8 # 2024-4-7  9:31-连接池最大空闲连接数
          min-idle: 0 # 2024-4-7  9:31-连接池最小空闲连接数
  cache:
    redis:
      time-to-live: 1800s
    cache-names: redis_cache
    type: redis
  jackson:
    serialization:
      # 2024-4-28  22:39-解决采用Jackson默认序列化方式序列化响应结果的时候序列化空字段对象时报错的问题
      fail-on-empty-beans: false
  cloud:
    # 2024-5-16  20:30-Sentinel相关配置
    sentinel:
      transport:
        dashboard: 127.0.0.1:9888 # 2024-5-16  20:30-关联Sentinel控制台
        # Sentinel 默认会对资源请求链路进行整合，这样会导致流控模式中的链路模式无法使用
        # 因此需要关闭 context 整合，这样 sentinel 监控界面会单独展示出每种链路请求路径
        # web-context-unify: false
      log:
        dir: D:\JavaProjects\ptp-web-backend\logs\sentinel\web\
        switch-pid: true # 2024-5-18  21:47-单机多模块必须启用该参数以区分各模块产生的日志


# 2024-3-16  19:33-Knife4j配置
knife4j:
  # enable: true # 2024-3-16  19:42-WebFlux模式下无法增强，运行将报 java.lang.ClassNotFoundException: jakarta.servlet.Filter 异常
  setting:
    language: zh_cn
  cors: true


# 2024-4-24  20:23-OpenAPI文档相关配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    csrf:
      enabled: true
    path: /swagger-ui.html


ptp:
  content:
    limit:
      passage-introduction-words-max-length: 35


# 2024-3-26  8:04-MyBatisPlus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: isDelete # 2024-3-26  8:08-全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）


# 2024-6-1  17:36-RocketMQ相关配置
rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: commodity-seckill-record-producer-group