# 2024-10-8  19:14-配置程序运行时可能用到的本机物理IP和其他服务的IP
ip:
  # 2024-10-8  19:16-物理IP
  physical:
    self-host: 192.168.1.10 # 2024-10-8  19:17-本机IP地址(除了修改此地方 , 还需要单独修改logback.xml中的IP配置)


# 2024-3-25  21:02-MyBatisPlus配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 2024-3-25  21:03-生产环境下需要关闭


spring:
  security:
    # 2024-4-7  20:20-配置开发环境下的OAuth2登录
    oauth2:
      client:
        registration:
          github:
            client-id: 4900da741269901ec6ca
            client-secret: 36133e1b6cf952a636cab52b78d1eba24e214fda


# 2024-5-30  22:26-设置RocketMQ的开发环境下的日志级别
logging:
  level:
    com.alibaba.cloud.stream.binder.rocketmq: info