# 2024-10-8  23:55-配置程序运行时可能用到的本机物理IP和其他服务的IP
ip:
  # 2024-10-8  23:55-物理IP
  physical:
    self-host: 192.168.1.10 # 2024-10-8  23:55-本机IP地址(除了修改此地方 , 还需要单独修改logback.xml中的IP配置)


# 2024-5-29  22:57-设置RocketMQ的开发环境下的日志级别
logging:
  level:
    com.alibaba.cloud.stream.binder.rocketmq: info