server:
  port: 8210
  servlet:
    context-path: /api/v1/service/mq


spring:
  cloud:
    # 2024-5-27  22:16-sentinel相关配置
    sentinel:
      transport:
        dashboard: 127.0.0.1:9888
      log:
        dir: D:\JavaProjects\ptp-web-backend\logs\sentinel\service\mq
        switch-pid: true

    # 2024-5-29  23:10-RocketMQ相关配置
    stream:
      #RocketMQ 通用配置
      rocketmq:
        binder:
          #客户端接入点，必填  rocketMQ的连接地址，binder高度抽象
          name-server: 127.0.0.1:9876
          # 不加, 会报错：Property 'group' is required - producerGroup
          group: ptp-web-service-mq-consumer
      #bindings 具体生产消息、消费消息的桥梁
      bindings:
        #Produce Config
        output: # 查看org.springframework.cloud.stream.config.BindingProperties
          destination: test-topic # topic消息主题
          contentType: application/json # 内容格式,默认是application/json
          group: test-group
        #Consumer Config
        input:
          destination: test-topic
          contentType: application/json #默认是application/json
          group: test-group


# 2024-5-27  22:16-Knife4j相关配置
knife4j:
  enable: true
  setting:
    language: zh_cn
  cors: true


# 2024-5-27  22:16-OpenAPI文档相关配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    csrf:
      enabled: true
    path: /swagger-ui.html