server:
  port: 8090
  servlet:
    context-path: /api/v1/service/store


spring:
  servlet:
    multipart:
      max-file-size: 100MB # 2024-4-24  18:07-单个上传的文件的最大大小
      max-request-size: 4096MB # 2024-4-24  18:07-总请求文件大小
  cloud:
    # 2024-5-18  21:52-sentinel相关配置
    sentinel:
      transport:
        dashboard: 127.0.0.1:9888
      log:
        dir: D:\JavaProjects\ptp-web-backend\logs\sentinel\service\store
        switch-pid: true


# 2024-4-23  20:38-Knife4j相关配置
knife4j:
  enable: true
  setting:
    language: zh_cn
  cors: true


# 2024-4-24  20:23-OpenAPI文档相关配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    csrf:
      enabled: true
    path: /swagger-ui.html


# 2024-4-23  21:28-minio相关配置
minio:
  endpoint: 127.0.0.1
  port: 9000
  secure: false
  access-key: ptp_minio_access_key
  secret-key: ptp_minio_secret_key

