server:
  port: 8150
  servlet:
    context-path: /api/v1/service/gateway


spring:
  cloud:
    # 2024-4-30  19:04-spring.cloud.gateway网关配置
    gateway:
      discovery:
        locator:
          enabled: false # 2024-4-30  21:00-将网关配置为基于在 DiscoveryClient 兼容服务注册中心上注册的服务来创建路由(禁用该功能，防止用户意外地直接访问到其他非web的微服务)

      globalcors:
        cors-configurations:
          # 2024-4-30  21:0-对于所有类型的HTTP请求的路径，允许来自所有路径的请求的跨域请求
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods: [ "GET","POST","PUT","DELETE" ] # 2024-8-1  22:17-这个字段在简单请求的的时候比如get/post用*或者不写都可以，但是当使用 PUT/DELETE 请求的时候，必须明确规定写出来
            allowed-headers: "*"
            allow-credentials: true
        add-to-simple-url-handler-mapping: true # 2024-4-30  21:04-为未被某些网关路由谓词处理的请求提供相同的 CORS 配置
        # main:
        # web-application-type: reactive # 2024-4-30  21:59-解决本模块服务启动报 Spring MVC found on classpath, which is incompatible with Spring Cloud Gateway 错误的问题
    sentinel:
      # 2024-5-14  21:18-Sentinel 网关流控默认的粒度是 route 维度以及自定义 API 分组维度，默认不支持 URL 粒度。若通过 Spring Cloud Alibaba 接入，请将 spring.cloud.sentinel.filter.enabled 配置项置为 false
      # enabled: false
      transport:
        dashboard: ${ip.physical.self-host:127.0.0.1}:9888


    # 2024-4-4  20:30-集成Redis所需配置
  data:
    redis:
      host: ${ip.physical.self-host:127.0.0.1}
      port: 7001
      username: default
      password: root
      jedis:
        pool:
          max-active: 8 # 2024-4-7  9:29-连接池最大连接数
          max-wait: -1 # 2024-4-7  9:30-连接池最大阻塞空闲时间(负数表示无限制)
          max-idle: 8 # 2024-4-7  9:31-连接池最大空闲连接数
          min-idle: 0 # 2024-4-7  9:31-连接池最小空闲连接数

  # main:
    # allow-bean-definition-overriding: true # 2024-11-9  23:25-解决redisRateLimiter定义冲突的问题