# 2024-10-8  19:37-配置程序运行时可能用到的本机物理IP和其他服务的IP
ip:
  # 2024-10-8  19:37-物理IP
  physical:
    self-host: 192.168.1.10 # 2024-10-8  19:37-本机IP地址(除了修改此地方 , 还需要单独修改logback.xml中的IP配置)
    ptp-web-web-server-host: ${ip.physical.self-host} # 2024-11-9  21:55-PTP-WEB服务的服务器的IP地址
    ptp-web-service-server-host: ${ip.physical.self-host} # 2024-11-9  21:55-PTP-SERVICE服务的服务器的IP地址