server:
  port: 8150
  servlet:
    context-path: /api/v1/service/gateway


spring:
  cloud:
    # 2024-4-30  19:04-spring.cloud.gateway网关配置
    gateway:
      discovery:
        locator:
          enabled: false # 2024-4-30  21:00-将网关配置为基于在 DiscoveryClient 兼容服务注册中心上注册的服务来创建路由(禁用该功能，防止用户意外地直接访问到其他非web的微服务)

      globalcors:
        cors-configurations:
          # 2024-4-30  21:0-对于所有GET/POST/PUT/DELETE请求的路径，允许来自所有路径的请求的跨域请求
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
        add-to-simple-url-handler-mapping: true # 2024-4-30  21:04-为未被某些网关路由谓词处理的请求提供相同的 CORS 配置

      routes:
        # 2024-4-30  21:18-用户登录应无条件放行，即使用户已经登录，依旧可以覆盖掉旧数据登录
        - id: baidu
          uri: https://tieba.baidu.com
          predicates:
            - Path=/index.html
            - Method=GET
        # 2024-5-2  20:49-放行用户对web服务的直接访问
        - id: web-web
          uri: http://127.0.0.1:8080
          predicates:
            - Path=/api/v1/web/**
          metadata:
            response-timeout: 5000
            connect-timeout: 5000

      # main:
      # web-application-type: reactive # 2024-4-30  21:59-解决本模块服务启动报 Spring MVC found on classpath, which is incompatible with Spring Cloud Gateway 错误的问题


    # 2024-4-4  20:30-集成Redis所需配置
  data:
    redis:
      host: 127.0.0.1
      port: 7001
      username: default
      password: root
      jedis:
        pool:
          max-active: 8 # 2024-4-7  9:29-连接池最大连接数
          max-wait: -1 # 2024-4-7  9:30-连接池最大阻塞空闲时间(负数表示无限制)
          max-idle: 8 # 2024-4-7  9:31-连接池最大空闲连接数
          min-idle: 0 # 2024-4-7  9:31-连接池最小空闲连接数

# 2024-5-3  22:11-全局路径校验规则配置
ptp:
  web:
    paths:
      permitAll: # 2024-5-3  22:19-只能是末尾不带‘/’的路径前缀或全路径
        - "/api/v1/web/gate"
        - "/api/v1/web/doc.html"
        - "/api/v1/web/v3/api-docs"