-- 插入用户数据
INSERT INTO user (account, password, email, nickname, realName, gender, idiograph, avatar, background_picture, like_num,
                  user_rank, register_date, birth_date, address_info, bind_accounts, credit, status, meta, role, asset)
VALUES ('user1', 'password1', 'user1@example.com', 'JohnDoe', 'John Doe', 'MALE', 'I am a programmer.',
        '{"type":"url","uri":"https://example.com/avatar1.jpg"}',
        '{"type":"url","uri":"https://example.com/background1.jpg"}', 100, 4.5, '2022-01-01 10:00:00', '1990-05-15',
        '{"city":"New York","country":"USA"}', 'socialmedia@example.com', 200.5, 'ACTIVE', '{"key":"value"}', 'USER',
        '{"balance":10000, "stocks": [{"symbol": "AAPL", "quantity": 100}, {"symbol": "GOOGL", "quantity": 50}]}'),
       ('user2', 'password2', 'user2@example.com', 'JaneSmith', 'Jane Smith', 'FEMALE', 'I love hiking.',
        '{"type":"url","uri":"https://example.com/avatar2.jpg"}',
        '{"type":"url","uri":"https://example.com/background2.jpg"}', 150, 4.2, '2022-01-05 15:30:00', '1985-08-20',
        '{"city":"Los Angeles","country":"USA"}', 'ecommerce@example.com', 300.75, 'ACTIVE', '{"key":"value"}', 'USER',
        '{"balance":8000, "stocks": [{"symbol": "MSFT", "quantity": 75}, {"symbol": "AMZN", "quantity": 40}]}'),
       ('user3', 'password3', 'user3@example.com', 'DavidBrown', 'David Brown', 'MALE', 'Coffee lover.',
        '{"type":"url","uri":"https://example.com/avatar3.jpg"}',
        '{"type":"url","uri":"https://example.com/background3.jpg"}', 120, 4.0, '2022-01-10 12:45:00', '1995-03-10',
        '{"city":"London","country":"UK"}', 'business@example.com', 400.25, 'INACTIVE', '{"key":"value"}', 'USER',
        '{"balance":12000, "stocks": [{"symbol": "TSLA", "quantity": 30}, {"symbol": "NFLX", "quantity": 60}]}'),
       ('user4', 'password4', 'user4@example.com', 'EmmaWilson', 'Emma Wilson', 'FEMALE', 'Music enthusiast.',
        '{"type":"url","uri":"https://example.com/avatar4.jpg"}',
        '{"type":"url","uri":"https://example.com/background4.jpg"}', 80, 3.8, '2022-01-15 08:20:00', '1998-11-25',
        '{"city":"Paris","country":"France"}', 'musiclover@example.com', 150.35, 'ACTIVE', '{"key":"value"}', 'USER',
        '{"balance":5000, "stocks": [{"symbol": "FB", "quantity": 100}, {"symbol": "TWTR", "quantity": 30}]}'),
       ('user5', 'password5', 'user5@example.com', 'MichaelClark', 'Michael Clark', 'MALE', 'Tech geek.',
        '{"type":"url","uri":"https://example.com/avatar5.jpg"}',
        '{"type":"url","uri":"https://example.com/background5.jpg"}', 200, 4.8, '2022-01-20 17:00:00', '1992-09-12',
        '{"city":"Berlin","country":"Germany"}', 'tech@example.com', 600.45, 'ACTIVE', '{"key":"value"}', 'USER',
        '{"balance":15000, "stocks": [{"symbol": "GOOG", "quantity": 25}, {"symbol": "AAPL", "quantity": 80}]}'),
       ('admin1', 'adminpass1', 'admin1@example.com', 'Admin1', 'Admin One', 'MALE', 'Administrator.',
        '{"type":"url","uri":"https://example.com/admin1.jpg"}',
        '{"type":"url","uri":"https://example.com/admin1-background.jpg"}', 500, 5.0, '2022-01-25 09:45:00',
        '1980-04-05', '{"city":"Tokyo","country":"Japan"}', 'admin@example.com', 1000.0, 'ACTIVE', '{"key":"value"}',
        'ADMIN',
        '{"balance":50000, "stocks": [{"symbol": "AAPL", "quantity": 200}, {"symbol": "AMZN", "quantity": 100}]}'),
       ('admin2', 'adminpass2', 'admin2@example.com', 'Admin2', 'Admin Two', 'FEMALE', 'Administrator.',
        '{"type":"url","uri":"https://example.com/admin2.jpg"}',
        '{"type":"url","uri":"https://example.com/admin2-background.jpg"}', 550, 5.0, '2022-02-01 14:00:00',
        '1975-06-18', '{"city":"Seoul","country":"South Korea"}', 'admin@example.com', 1200.0, 'ACTIVE',
        '{"key":"value"}', 'ADMIN',
        '{"balance":60000, "stocks": [{"symbol": "GOOGL", "quantity": 150}, {"symbol": "TSLA", "quantity": 80}]}'),
       ('admin3', 'adminpass3', 'admin3@example.com', 'Admin3', 'Admin Three', 'MALE', 'Administrator.',
        '{"type":"url","uri":"https://example.com/admin3.jpg"}',
        '{"type":"url","uri":"https://example.com/admin3-background.jpg"}', 600, 5.0, '2022-02-05 11:30:00',
        '1970-10-30', '{"city":"Beijing","country":"China"}', 'admin@example.com', 1500.0, 'ACTIVE', '{"key":"value"}',
        'ADMIN',
        '{"balance":70000, "stocks": [{"symbol": "MSFT", "quantity": 120}, {"symbol": "NFLX", "quantity": 90}]}');
